export default function generateChallenge(){
    const challenges: [string, number][] = [
        ["Get to a place 10 ft or more above the ground, get taggers to agree it is 10ft+, take a picture from the top of it, and send it in the group chat", 1],
        ["Review a nearby structure on video based on aesthetic, build, appeal, and importance in great detail with at least 5 sentences for each property", 1],
        ["Remain still in the exact spot you are in right now without moving for the next 2 minutes", 2],
        ["From the moment you draw this challenge, you have 2:30 minutes to find as many street signs as you can, video call the whole process, if you find less than 6, then you must autoveto this card and wait 5 minutes to draw another card, each individual sign on a pole counts as a street sign", 2],
        ["Yell MEOWW in a public place, You must get on video call with one of the taggers to prove you are yelling, the public place does not have to be populated, just a public place, from there you must yell", 1],
        ["FREEEEEEE POIIIIIINT, after informing the taggers you got this card, immediately draw your next card", 1],
        ["Make a shot in a basketball hoop with any item", 2],
        ["Hold a conversation with a stranger for 90 seconds (must be on call for proof)", 2],
        ["Enter any store", 1],
        ["Find an item in a store worth more than 50 dollars and take a picture with it", 2],
        ["Make a stranger laugh, you must prove you made them laugh either with a picture or by getting on call", 3],
        ["Go to Alma Mater", 2],
        ["Gather one mile of distance (not necessarily in a straight line) inside of the game area", 2],
        ["Bury any treasure, the \"treasure\" can either be created by you or found on the ground but must be rare and unique (send a picture of this in the groupchat to verify), you must bury the treasure more than 4 inches under the ground", 3],
        ["UNLUCKY!!! You may not complete challenges for 5 minutes, after 5 minutes you may draw your next card, if vetoed, along with waiting 5 minutes, you also lose 1 point unless you currently have 0 points", 0],
        ["Freestyle a 3 minute long song on a voice call with the taggers", 1],
        ["Get a stranger to say idli to you without saying the word idli at all", 4],
        ["Take a funny picture with a random person you don't know. Must be considered funny by at least 2 tagger teams", 2],
        ["Take a selfie with another team in the picture, if they do not tag you before you take the selfie then they are frozen for 3 minutes", 1],
        ["Get tagged, you steal the 3 points you gain from whoever tags you, if the person tagging you has less than 3 points, you steal only the points they have until they have 0 points", 3],
        ["Find a cool rock and hold it for 3 minutes", 2],
        ["Pick up 5 pieces of litter and throw it away in 5 minutes", 3],
        ["Convince 5 friends to send you pictures of beans in their apartment", 2],
        ["Win a round of any mobile game, you must take a screenshot and send it in the chat", 1],
        ["Find a stranger to do the Macarena with you on video", 2],
        ["Hit different fortnite dances as a group for a total of 3 minutes", 3],
        ["Find a pokemon go player currently playing the game, and take a picture of them playing, it can be yourself if you load up pokemon go and play it", 1],
        ["Go drink water (picture required), this challenge cannot be vetoed and a new challenge cannot be completed until you complete this challenge", 0],
        ["Do whatever challenge you just did, if you didn't do any challenge yet then skip this card with no consequence", 1],
        ["LUCKKYYYYY taggers must all say all of their tentative courses for next semester, 1 at a time, runner times them, for every 30 seconds they take, runner gets 0.25 points", 0.25],
        ["Must touch a bag of chips, stays in effect until you touch the bag of chips", 2],
        ["Go around pretending you're a street interviewer and do 3 interviews for 1 minute each", 4],
        ["Get on a call with taggers and name songs of a chosen artist you both agree on, if you name more, get 2 points if they name more, stand still for 2 min and can't choose another challenge until that time ends", 2],
        ["Roll around in grass (prove with a video)", 1],
        ["Sing a full Bruno mars song on call or on video. You can search up lyrics, if at any point you stop before the end of the song you must restart", 2],
        ["Give a hi five to any person not playing the game, send a picture as proof", 2],
        ["Take a picture with a statue or public art installation", 2],
        ["Do 10 jumping jacks in a public place, video required", 2],
        ["Find a playground and go down a slide, send a video", 2],
        ["Draw a chalk drawing on the sidewalk and send a picture", 2],
        ["Find a dog wearing clothes and take a selfie with it", 3],
        ["Find a license plate from another state and send a picture", 1],
        ["Find a flower and give it to a stranger, get a picture", 2],
        ["Find a store employee and ask for their favorite product, video required", 2],
        ["Take a picture with a bicycle (yours or someone else's)", 1],
        ["Find a bridge and walk across it, send proof", 2],
        ["Find a bus stop and wait there for 2 minutes, send proof", 1],
        ["Find a mailbox and take a selfie with it", 1],
        ["Find a sign in a language other than English, send a picture", 1],
        ["Find a person with a pet other than a dog, take a picture", 2],
        ["Find a public staircase and walk up and down, send proof", 2],
    ];


    const rnum = Math.floor(Math.random() * challenges.length);

    return [String(rnum+1) + ": " + challenges[rnum][0], challenges[rnum][1]]; 
}
